/*
 * KonkodLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.www.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class ClientCredentials 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 3848482097353575083L;
    private String clientId;
    private String clientSecret;
    private String grantType;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("clientId")
    public String getClientId ( ) { 
        return this.clientId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("clientId")
    public void setClientId (String value) { 
        this.clientId = value;
        notifyObservers(this.clientId);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("clientSecret")
    public String getClientSecret ( ) { 
        return this.clientSecret;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("clientSecret")
    public void setClientSecret (String value) { 
        this.clientSecret = value;
        notifyObservers(this.clientSecret);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("grantType")
    public String getGrantType ( ) { 
        return this.grantType;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("grantType")
    public void setGrantType (String value) { 
        this.grantType = value;
        notifyObservers(this.grantType);
    }
 
}
