/*
 * KonkodLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.www.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class JWTToken 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 4145572527846606951L;
    private String accessToken;
    private String tokeType;
    private Long expiresIn;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("accessToken")
    public String getAccessToken ( ) { 
        return this.accessToken;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("accessToken")
    public void setAccessToken (String value) { 
        this.accessToken = value;
        notifyObservers(this.accessToken);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("tokeType")
    public String getTokeType ( ) { 
        return this.tokeType;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("tokeType")
    public void setTokeType (String value) { 
        this.tokeType = value;
        notifyObservers(this.tokeType);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("expiresIn")
    public Long getExpiresIn ( ) { 
        return this.expiresIn;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("expiresIn")
    public void setExpiresIn (Long value) { 
        this.expiresIn = value;
        notifyObservers(this.expiresIn);
    }
 
}
