/*
 * KonkodLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.www.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class Konkod 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = -1959823986327396385L;
    private Long konkodId;
    private Long statusId;
    private String instutionName;
    private String image;
    private String departman;
    private String person;
    private String code;
    private String insertionDate;
    private String updatedDate;
    private Long star1;
    private Long star2;
    private Long star3;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("konkodId")
    public Long getKonkodId ( ) { 
        return this.konkodId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("konkodId")
    public void setKonkodId (Long value) { 
        this.konkodId = value;
        notifyObservers(this.konkodId);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("statusId")
    public Long getStatusId ( ) { 
        return this.statusId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("statusId")
    public void setStatusId (Long value) { 
        this.statusId = value;
        notifyObservers(this.statusId);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("instutionName")
    public String getInstutionName ( ) { 
        return this.instutionName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("instutionName")
    public void setInstutionName (String value) { 
        this.instutionName = value;
        notifyObservers(this.instutionName);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("image")
    public String getImage ( ) { 
        return this.image;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("image")
    public void setImage (String value) { 
        this.image = value;
        notifyObservers(this.image);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("departman")
    public String getDepartman ( ) { 
        return this.departman;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("departman")
    public void setDepartman (String value) { 
        this.departman = value;
        notifyObservers(this.departman);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("person")
    public String getPerson ( ) { 
        return this.person;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("person")
    public void setPerson (String value) { 
        this.person = value;
        notifyObservers(this.person);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("code")
    public String getCode ( ) { 
        return this.code;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("code")
    public void setCode (String value) { 
        this.code = value;
        notifyObservers(this.code);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("insertionDate")
    public String getInsertionDate ( ) { 
        return this.insertionDate;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("insertionDate")
    public void setInsertionDate (String value) { 
        this.insertionDate = value;
        notifyObservers(this.insertionDate);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("updatedDate")
    public String getUpdatedDate ( ) { 
        return this.updatedDate;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("updatedDate")
    public void setUpdatedDate (String value) { 
        this.updatedDate = value;
        notifyObservers(this.updatedDate);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("star1")
    public Long getStar1 ( ) { 
        return this.star1;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("star1")
    public void setStar1 (Long value) { 
        this.star1 = value;
        notifyObservers(this.star1);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("star2")
    public Long getStar2 ( ) { 
        return this.star2;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("star2")
    public void setStar2 (Long value) { 
        this.star2 = value;
        notifyObservers(this.star2);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("star3")
    public Long getStar3 ( ) { 
        return this.star3;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("star3")
    public void setStar3 (Long value) { 
        this.star3 = value;
        notifyObservers(this.star3);
    }
 
}
