/*
 * KonkodLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.www.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class User 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = -2741265859270862400L;
    private Long userId;
    private String phone;
    private String fcmRegistrationId;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("userId")
    public Long getUserId ( ) { 
        return this.userId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("userId")
    public void setUserId (Long value) { 
        this.userId = value;
        notifyObservers(this.userId);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("phone")
    public String getPhone ( ) { 
        return this.phone;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("phone")
    public void setPhone (String value) { 
        this.phone = value;
        notifyObservers(this.phone);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("fcmRegistrationId")
    public String getFcmRegistrationId ( ) { 
        return this.fcmRegistrationId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("fcmRegistrationId")
    public void setFcmRegistrationId (String value) { 
        this.fcmRegistrationId = value;
        notifyObservers(this.fcmRegistrationId);
    }
 
}
