/*
 * KonkodLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.www;

import com.example.www.controllers.*;
import com.example.www.http.client.HttpClient;

public class KonkodClient {
    /**
     * Singleton access to User controller
     * @return	Returns the UserController instance 
     */
    public UserController getUser() {
        return UserController.getInstance();
    }

    /**
     * Singleton access to Survey controller
     * @return	Returns the SurveyController instance 
     */
    public SurveyController getSurvey() {
        return SurveyController.getInstance();
    }

    /**
     * Singleton access to Konkod controller
     * @return	Returns the KonkodController instance 
     */
    public KonkodController getKonkod() {
        return KonkodController.getInstance();
    }

    /**
     * Singleton access to Authentication controller
     * @return	Returns the AuthenticationController instance 
     */
    public AuthenticationController getAuthentication() {
        return AuthenticationController.getInstance();
    }

    /**
     * Get the shared http client currently being used for API calls
     * @return The http client instance currently being used
     */
    public HttpClient getSharedHttpClient() {
        return BaseController.getClientInstance();
    }
    
    /**
     * Set a shared http client to be used for API calls
     * @param httpClient The http client to use
     */
    public void setSharedHttpClient(HttpClient httpClient) {
        BaseController.setClientInstance(httpClient);
    }

    /**
     * Default constructor 
     */     
    public KonkodClient() {
    }

    /**
     * Client initialization constructor 
     */     
    public KonkodClient(String authorization) {
        this();
        Configuration.authorization = authorization;
    }
}